version: '3.8'

services:
  discordttcbot:
    image: ghcr.io/xenyc1337/discordttcbot:latest
    container_name: discordttcbot
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - API_KEY=${API_KEY}
    restart: always